mosip.api.internal.url=https://api-internal-niradev1.idencode.link
mosip.iam.base.url=https://iam-niradev1.idencode.link
#local
#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.username=regprcuser
#spring.datasource.password=${db.dbuser.password}
#spring.datasource.driver-class-name=org.postgresql.Driver

#postgres
spring.datasource.url=jdbc:postgresql://postgres-postgresql.postgres:5432/mosip_keymgr
spring.datasource.username=keymgruser
spring.datasource.password=${db.dbuser.password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

mosip.keymgr.expiry-notification.cron=0 * * * * ?

spring.main.allow-bean-definition-overriding=true

mosip.keymgr.expiry-notification.email.notification.url=${mosip.api.internal.url}/v1/notifier/email/send
mosip.keymgr.expiry-notification.recipients=malay.pandey@technoforte.co.in,soumya.raj@technoforte.co.in,jivesh.kumar@technoforte.co.in
mosip.auth.adapter.impl.basepackage=io.mosip.kernel.auth.defaultadapter
mosip.kernel.auth.appids.realm.map={regproc:'mosip'}
auth.server.admin.issuer.uri=${keycloak.external.url}/auth/realms/
mosip.iam.adapter.appid=regproc
mosip.iam.adapter.clientid=mosip-regproc-client
mosip.iam.adapter.clientsecret=${mosip.regproc.client.secret}
mosip.kernel.auth.adapter.ssl-bypass=true
auth.server.admin.allowed.audience=mosip-regproc-client
mosip.kernel.auth.appid-realm-map={regproc:'mosip'}


#keykloak
mosip.iam.open-id-url=${keycloak.external.url}/auth/realms/{realmId}/protocol/openid-connect/
mosip.iam.master.realm-id=master
mosip.keycloak.admin.client.id=admin-cli
mosip.keycloak.admin.user.id=admin
mosip.keycloak.admin.secret.key=${keycloak.admin.password}
#keycloak.admin.password=yF0fMpQbm2
